import type { University } from "./types";

export const CATALOG_NOTE =
  "Figures below are a demo catalog compiled for this prototype (2025–26 cycle snapshot). Confirm every deadline, fee, and aid rule on the university site before you apply.";

export const FIT_METHODOLOGY =
  "Fit index is a 0–100 weighted score: academic overlap 30%, aid feasibility 25%, location 20%, research alignment 15%, testing/language 10%. It is not an admissions probability and does not predict a decision.";

export const universities: University[] = [
  {
    id: "nyuad",
    name: "NYU Abu Dhabi",
    shortName: "NYUAD",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
    countryId: "ae",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "generous-need",
      summary:
        "Need-aware admissions with substantial need-based aid for admitted students, including internationals.",
    },
    tuitionIntlUsd: 62000,
    tuitionNote: "Sticker price is high; aid can cover a large share of demonstrated need.",
    selectivity: "extremely",
    application: "Common App",
    deadlines: [
      { label: "Early Decision I", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 5" },
    ],
    english: "TOEFL, IELTS, or Duolingo accepted if schooling was not in English.",
    notes:
      "Residential liberal-arts campus with funded undergraduate research and a global network.",
    sources: [
      {
        label: "NYUAD admissions",
        url: "https://nyuad.nyu.edu/en/admissions.html",
      },
      {
        label: "NYUAD financial aid",
        url: "https://nyuad.nyu.edu/en/admissions/financial-aid.html",
      },
    ],
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    city: "Cambridge",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "biology", "economics", "undecided"],
    research: "high",
    aid: {
      kind: "meets-full-need",
      summary:
        "Need-blind for all applicants, including internationals, and commits to meeting full demonstrated need.",
    },
    tuitionIntlUsd: 62000,
    tuitionNote: "Aid is need-based. International students are eligible.",
    selectivity: "extremely",
    application: "MIT application (not Common App)",
    deadlines: [
      { label: "Early Action", date: "Nov 1" },
      { label: "Regular Action", date: "Jan 6" },
    ],
    english: "English proficiency required if English is not the language of instruction.",
    notes:
      "Undergraduate research (UROP) is a core part of the academic culture.",
    sources: [
      { label: "MIT admissions", url: "https://mitadmissions.org/" },
      {
        label: "MIT student financial services",
        url: "https://sfs.mit.edu/",
      },
    ],
  },
  {
    id: "waterloo",
    name: "University of Waterloo",
    shortName: "Waterloo",
    city: "Waterloo",
    country: "Canada",
    countryId: "ca",
    programs: ["cs", "engineering", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "International tuition is high; entrance awards exist, but full-need packages are uncommon.",
    },
    tuitionIntlUsd: 48000,
    tuitionNote: "Co-op earnings can offset cost; they are not a substitute for aid.",
    selectivity: "very",
    application: "OUAC 105",
    deadlines: [{ label: "Most programs", date: "Jan 15" }],
    english: "IELTS 6.5 typical minimum; higher for some programs.",
    notes: "Co-op is the distinctive feature, especially in computer science and engineering.",
    sources: [
      {
        label: "Waterloo undergraduate admissions",
        url: "https://uwaterloo.ca/undergraduate-admissions/",
      },
      {
        label: "Waterloo international fees",
        url: "https://uwaterloo.ca/student-financial-services/",
      },
    ],
  },
  {
    id: "toronto",
    name: "University of Toronto",
    shortName: "U of T",
    city: "Toronto",
    country: "Canada",
    countryId: "ca",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Some international scholarships (including Lester B. Pearson) are available; most students pay international tuition.",
    },
    tuitionIntlUsd: 45000,
    tuitionNote: "Need-based aid for internationals is limited relative to U.S. private colleges.",
    selectivity: "very",
    application: "OUAC",
    deadlines: [{ label: "International applicants", date: "Jan 15" }],
    english: "IELTS / TOEFL accepted; program minima vary.",
    notes: "Large research university with strong CS, economics, and life sciences.",
    sources: [
      {
        label: "U of T future students",
        url: "https://future.utoronto.ca/",
      },
    ],
  },
  {
    id: "brown",
    name: "Brown University",
    shortName: "Brown",
    city: "Providence",
    country: "United States",
    countryId: "us",
    programs: ["cs", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "need-aware-intl",
      summary:
        "Meets full demonstrated need for admitted students; international admissions are need-aware.",
    },
    tuitionIntlUsd: 68000,
    tuitionNote: "If admitted with need, Brown typically meets 100% of demonstrated need.",
    selectivity: "extremely",
    application: "Common App",
    deadlines: [
      { label: "Early Decision", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 5" },
    ],
    english: "Testing policy varies by year; confirm English-proficiency rules.",
    notes: "Open Curriculum. Strong if you want research without a rigid core.",
    sources: [
      { label: "Brown admission", url: "https://admission.brown.edu/" },
      {
        label: "Brown financial aid",
        url: "https://www.brown.edu/admission/undergraduate/apply/financial-aid",
      },
    ],
  },
  {
    id: "gatech",
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    city: "Atlanta",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Public university; international students have limited access to institutional need-based aid.",
    },
    tuitionIntlUsd: 33000,
    tuitionNote: "Lower sticker than many private U.S. schools, but still a stretch without aid.",
    selectivity: "very",
    application: "Common App / Coalition",
    deadlines: [
      { label: "Early Action", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 4" },
    ],
    english: "TOEFL/IELTS required unless exempt.",
    notes: "Particularly strong for computing and engineering.",
    sources: [
      { label: "Georgia Tech admission", url: "https://admission.gatech.edu/" },
    ],
  },
  {
    id: "ucl",
    name: "University College London",
    shortName: "UCL",
    city: "London",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "A small number of international scholarships exist; most undergraduates pay overseas fees.",
    },
    tuitionIntlUsd: 38000,
    tuitionNote: "Fees vary by department. Scholarships are competitive, not need-guaranteed.",
    selectivity: "very",
    application: "UCAS",
    deadlines: [{ label: "UCAS equal consideration", date: "Jan 14" }],
    english: "IELTS Academic typically 6.5–7.5 depending on programme.",
    notes: "Broad research university in central London. Programme-specific entry requirements.",
    sources: [
      { label: "UCL undergraduate", url: "https://www.ucl.ac.uk/prospective-students/undergraduate" },
    ],
  },
  {
    id: "lse",
    name: "London School of Economics",
    shortName: "LSE",
    city: "London",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["economics", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary: "Scholarships exist but are competitive; full-need aid is not the default.",
    },
    tuitionIntlUsd: 35000,
    tuitionNote: "Overseas fees are programme-specific.",
    selectivity: "extremely",
    application: "UCAS",
    deadlines: [{ label: "UCAS equal consideration", date: "Jan 14" }],
    english: "IELTS usually 7.0 overall for undergraduate programmes.",
    notes: "Specialist social-science university. Weak fit if the only interest is systems CS.",
    sources: [
      { label: "LSE undergraduate", url: "https://www.lse.ac.uk/study-at-lse/Undergraduate" },
    ],
  },
  {
    id: "tudelft",
    name: "TU Delft",
    shortName: "TU Delft",
    city: "Delft",
    country: "Netherlands",
    countryId: "nl",
    programs: ["cs", "engineering"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary:
        "Statutory fees for EU; institutional fees for non-EU are far below U.S. private tuition.",
    },
    tuitionIntlUsd: 17000,
    tuitionNote: "Non-EU bachelor fees are typically in the mid-teens (USD), not full-need aid.",
    selectivity: "moderately",
    application: "Studielink / university portal",
    deadlines: [{ label: "Non-EU bachelor (typical)", date: "Jan 15" }],
    english: "IELTS/TOEFL required for English-taught programmes.",
    notes: "Engineering-first campus. Numerus fixus for some programmes.",
    sources: [
      { label: "TU Delft bachelor", url: "https://www.tudelft.nl/en/education/programmes/bachelors" },
    ],
  },
  {
    id: "tum",
    name: "Technical University of Munich",
    shortName: "TUM",
    city: "Munich",
    country: "Germany",
    countryId: "de",
    programs: ["cs", "engineering", "biology"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary: "Public tuition is low; living costs in Munich are the real budget item.",
    },
    tuitionIntlUsd: 3000,
    tuitionNote: "Bavaria may charge modest fees for non-EU students; still far below private U.S. costs.",
    selectivity: "moderately",
    application: "TUMonline / uni-assist (programme-dependent)",
    deadlines: [{ label: "Winter semester (typical)", date: "May 31" }],
    english: "Many bachelor programmes are German-taught; check language of instruction.",
    notes: "Excellent technical education; language of instruction is a real constraint.",
    sources: [
      { label: "TUM degree programs", url: "https://www.tum.de/en/studies" },
    ],
  },
  {
    id: "eth",
    name: "ETH Zurich",
    shortName: "ETH",
    city: "Zurich",
    country: "Switzerland",
    countryId: "ch",
    programs: ["cs", "engineering", "biology"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary: "Tuition is low by international standards; Zurich living costs are high.",
    },
    tuitionIntlUsd: 1600,
    tuitionNote: "Tuition is not the barrier; language (German at bachelor level) and living costs are.",
    selectivity: "very",
    application: "ETH application portal",
    deadlines: [{ label: "Bachelor autumn (typical)", date: "Apr 30" }],
    english: "Bachelor programmes are primarily German-taught.",
    notes: "World-class technical university. Language of instruction matters more than tuition.",
    sources: [
      { label: "ETH bachelor admission", url: "https://ethz.ch/en/studies/bachelor.html" },
    ],
  },
  {
    id: "minerva",
    name: "Minerva University",
    shortName: "Minerva",
    city: "Multiple cities",
    country: "United States (global rotation)",
    countryId: "us",
    programs: ["cs", "economics", "biology", "undecided"],
    research: "moderate",
    aid: {
      kind: "generous-need",
      summary: "Sticker tuition is below many privates; need-based aid is available for internationals.",
    },
    tuitionIntlUsd: 23500,
    tuitionNote: "Aid plus lower sticker can make this viable when full private U.S. aid is unlikely.",
    selectivity: "very",
    application: "Minerva application",
    deadlines: [{ label: "Round 1 (typical)", date: "Nov 1" }],
    english: "English is the language of instruction; proficiency is assessed in-app.",
    notes: "Not a traditional campus. Rotation across cities. Distinct pedagogy.",
    sources: [
      { label: "Minerva admissions", url: "https://www.minerva.edu/admissions/" },
    ],
  },
  {
    id: "princeton",
    name: "Princeton University",
    shortName: "Princeton",
    city: "Princeton",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "meets-full-need",
      summary:
        "Need-blind for all applicants, including internationals, and commits to meeting full demonstrated need.",
    },
    tuitionIntlUsd: 62000,
    tuitionNote: "Need-based aid covers demonstrated need; no-loan policies apply for many families.",
    selectivity: "extremely",
    application: "Common App / QuestBridge",
    deadlines: [
      { label: "Single-choice Early Action", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 1" },
    ],
    english: "English proficiency may be required if schooling was not in English.",
    notes: "Strong undergraduate focus with funded research across STEM and social sciences.",
    sources: [
      { label: "Princeton admission", url: "https://admission.princeton.edu/" },
      { label: "Princeton financial aid", url: "https://admission.princeton.edu/cost-aid" },
    ],
  },
  {
    id: "stanford",
    name: "Stanford University",
    shortName: "Stanford",
    city: "Stanford",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "need-aware-intl",
      summary:
        "Meets full demonstrated need for admitted students; international admissions are need-aware.",
    },
    tuitionIntlUsd: 65000,
    tuitionNote: "If admitted with need, Stanford typically meets 100% of demonstrated need.",
    selectivity: "extremely",
    application: "Common App / Coalition",
    deadlines: [
      { label: "Restrictive Early Action", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 5" },
    ],
    english: "TOEFL/IELTS may be requested when English is not the primary language of instruction.",
    notes: "Particularly strong for computing, engineering, and entrepreneurship-adjacent pathways.",
    sources: [
      { label: "Stanford undergraduate admission", url: "https://admission.stanford.edu/" },
    ],
  },
  {
    id: "caltech",
    name: "California Institute of Technology",
    shortName: "Caltech",
    city: "Pasadena",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "meets-full-need",
      summary:
        "Need-blind for all applicants and commits to meeting full demonstrated need, including internationals.",
    },
    tuitionIntlUsd: 63000,
    tuitionNote: "Aid is need-based. International students are eligible.",
    selectivity: "extremely",
    application: "Common App / Coalition",
    deadlines: [
      { label: "Early Action", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 3" },
    ],
    english: "English proficiency documentation may be required.",
    notes: "Small, research-intensive STEM campus. Core curriculum is demanding.",
    sources: [
      { label: "Caltech admissions", url: "https://www.admissions.caltech.edu/" },
    ],
  },
  {
    id: "cmu",
    name: "Carnegie Mellon University",
    shortName: "CMU",
    city: "Pittsburgh",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Institutional need-based aid for internationals is limited; merit awards exist but are competitive.",
    },
    tuitionIntlUsd: 64000,
    tuitionNote: "High sticker; internationals should not assume full-need packages.",
    selectivity: "extremely",
    application: "Common App",
    deadlines: [
      { label: "Early Decision", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 2" },
    ],
    english: "TOEFL/IELTS or Duolingo typically required unless exempt.",
    notes: "Especially strong for computer science, robotics, and related computing fields.",
    sources: [
      { label: "CMU undergraduate admission", url: "https://admission.enrollment.cmu.edu/" },
    ],
  },
  {
    id: "uiuc",
    name: "University of Illinois Urbana-Champaign",
    shortName: "UIUC",
    city: "Urbana-Champaign",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Public flagship; international students primarily pay non-resident tuition with limited need-based aid.",
    },
    tuitionIntlUsd: 36000,
    tuitionNote: "Lower sticker than many private U.S. schools, but still costly without scholarships.",
    selectivity: "very",
    application: "Common App / myIllini",
    deadlines: [
      { label: "Early Action", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 5" },
    ],
    english: "TOEFL/IELTS/Duolingo accepted; minima vary by college.",
    notes: "Large research university with a particularly well-known CS program.",
    sources: [
      { label: "UIUC undergraduate admissions", url: "https://www.admissions.illinois.edu/" },
    ],
  },
  {
    id: "michigan",
    name: "University of Michigan",
    shortName: "Michigan",
    city: "Ann Arbor",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Need-based aid for internationals is limited; some scholarships exist but are not full-need guarantees.",
    },
    tuitionIntlUsd: 58000,
    tuitionNote: "Out-of-state / international tuition is high relative to public in-state rates.",
    selectivity: "very",
    application: "Common App",
    deadlines: [
      { label: "Early Action", date: "Nov 1" },
      { label: "Regular Decision", date: "Feb 1" },
    ],
    english: "English proficiency required unless exempt by prior instruction.",
    notes: "Broad research university with strength across engineering, CS, and life sciences.",
    sources: [
      { label: "U-M undergraduate admissions", url: "https://admissions.umich.edu/" },
    ],
  },
  {
    id: "berkeley",
    name: "University of California, Berkeley",
    shortName: "UC Berkeley",
    city: "Berkeley",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "UC campuses offer limited institutional need-based aid to undocumented/international undergraduates.",
    },
    tuitionIntlUsd: 48000,
    tuitionNote: "Nonresident tuition plus living costs in the Bay Area are substantial.",
    selectivity: "extremely",
    application: "UC Application",
    deadlines: [{ label: "UC application", date: "Nov 30" }],
    english: "TOEFL/IELTS typically required for international applicants.",
    notes: "Very strong across CS, engineering, economics, and biological sciences.",
    sources: [
      { label: "UC Berkeley admissions", url: "https://admissions.berkeley.edu/" },
    ],
  },
  {
    id: "amherst",
    name: "Amherst College",
    shortName: "Amherst",
    city: "Amherst",
    country: "United States",
    countryId: "us",
    programs: ["cs", "economics", "biology", "undecided"],
    research: "moderate",
    aid: {
      kind: "meets-full-need",
      summary:
        "Need-blind for all applicants, including internationals, and meets full demonstrated need.",
    },
    tuitionIntlUsd: 67000,
    tuitionNote: "Aid is need-based; open curriculum-style flexibility within a liberal-arts setting.",
    selectivity: "extremely",
    application: "Common App / QuestBridge",
    deadlines: [
      { label: "Early Decision", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 3" },
    ],
    english: "English proficiency may be required if prior schooling was not in English.",
    notes: "Selective liberal-arts college with Five College research and course-sharing options.",
    sources: [
      { label: "Amherst admission", url: "https://www.amherst.edu/admission" },
    ],
  },
  {
    id: "rice",
    name: "Rice University",
    shortName: "Rice",
    city: "Houston",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "need-aware-intl",
      summary:
        "Meets full demonstrated need for admitted students; international admissions are need-aware.",
    },
    tuitionIntlUsd: 58000,
    tuitionNote: "If admitted with need, Rice typically meets demonstrated need.",
    selectivity: "extremely",
    application: "Common App / Coalition",
    deadlines: [
      { label: "Early Decision I", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 4" },
    ],
    english: "TOEFL/IELTS/Duolingo accepted when required.",
    notes: "Research university with residential colleges and strong STEM options.",
    sources: [
      { label: "Rice admission", url: "https://admission.rice.edu/" },
    ],
  },
  {
    id: "duke",
    name: "Duke University",
    shortName: "Duke",
    city: "Durham",
    country: "United States",
    countryId: "us",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "need-aware-intl",
      summary:
        "Meets full demonstrated need for admitted students; international admissions are need-aware.",
    },
    tuitionIntlUsd: 66000,
    tuitionNote: "Need-based aid is available after admission; internationals compete in a need-aware pool.",
    selectivity: "extremely",
    application: "Common App / Coalition",
    deadlines: [
      { label: "Early Decision", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 2" },
    ],
    english: "English proficiency testing may be required.",
    notes: "Strong across biomedical research, engineering, CS, and economics.",
    sources: [
      { label: "Duke undergraduate admissions", url: "https://admissions.duke.edu/" },
    ],
  },
  {
    id: "imperial",
    name: "Imperial College London",
    shortName: "Imperial",
    city: "London",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["cs", "engineering", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Competitive scholarships exist; most overseas undergraduates pay full international fees.",
    },
    tuitionIntlUsd: 42000,
    tuitionNote: "Fees are department-specific and typically high for STEM programmes.",
    selectivity: "extremely",
    application: "UCAS",
    deadlines: [{ label: "UCAS equal consideration", date: "Jan 14" }],
    english: "IELTS Academic typically 6.5–7.0 depending on course.",
    notes: "STEM-focused university. Programme entry requirements are course-specific.",
    sources: [
      {
        label: "Imperial undergraduate study",
        url: "https://www.imperial.ac.uk/study/courses/undergraduate/",
      },
    ],
  },
  {
    id: "edinburgh",
    name: "University of Edinburgh",
    shortName: "Edinburgh",
    city: "Edinburgh",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary: "Some international scholarships are available; full-need aid is not the default.",
    },
    tuitionIntlUsd: 36000,
    tuitionNote: "Overseas fees vary by subject; confirm the programme fee page.",
    selectivity: "very",
    application: "UCAS",
    deadlines: [{ label: "UCAS equal consideration", date: "Jan 14" }],
    english: "IELTS typically 6.5 overall for many undergraduate programmes.",
    notes: "Broad research university with strength in informatics and life sciences.",
    sources: [
      {
        label: "Edinburgh undergraduate",
        url: "https://www.ed.ac.uk/studying/undergraduate",
      },
    ],
  },
  {
    id: "cambridge",
    name: "University of Cambridge",
    shortName: "Cambridge",
    city: "Cambridge",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "College and university awards exist; most overseas students still face full international fees.",
    },
    tuitionIntlUsd: 40000,
    tuitionNote: "Fees depend on Tripos; living costs and college charges are additional.",
    selectivity: "extremely",
    application: "UCAS (+ Cambridge-specific steps)",
    deadlines: [{ label: "UCAS (Cambridge)", date: "Oct 15" }],
    english: "IELTS usually 7.5 overall for undergraduate courses (confirm by course).",
    notes: "College-based system with interviews and course-specific admissions assessments.",
    sources: [
      { label: "Cambridge undergraduate study", url: "https://www.undergraduate.study.cam.ac.uk/" },
    ],
  },
  {
    id: "oxford",
    name: "University of Oxford",
    shortName: "Oxford",
    city: "Oxford",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Scholarships (including some full awards) are competitive; most overseas students pay full fees.",
    },
    tuitionIntlUsd: 40000,
    tuitionNote: "Course fees and college fees vary; confirm the course page.",
    selectivity: "extremely",
    application: "UCAS (+ Oxford-specific steps)",
    deadlines: [{ label: "UCAS (Oxford)", date: "Oct 15" }],
    english: "IELTS typically 7.0–7.5 depending on course.",
    notes: "Tutorial system. Admissions tests and interviews are central.",
    sources: [
      { label: "Oxford undergraduate admissions", url: "https://www.ox.ac.uk/admissions/undergraduate" },
    ],
  },
  {
    id: "manchester",
    name: "University of Manchester",
    shortName: "Manchester",
    city: "Manchester",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary: "International scholarships exist but are competitive; need-guaranteed aid is uncommon.",
    },
    tuitionIntlUsd: 32000,
    tuitionNote: "Overseas fees are programme-specific and often below London peers.",
    selectivity: "very",
    application: "UCAS",
    deadlines: [{ label: "UCAS equal consideration", date: "Jan 14" }],
    english: "IELTS typically 6.0–6.5 for many undergraduate programmes.",
    notes: "Large research university with broad STEM and social-science coverage.",
    sources: [
      {
        label: "Manchester undergraduate",
        url: "https://www.manchester.ac.uk/study/undergraduate/",
      },
    ],
  },
  {
    id: "mcgill",
    name: "McGill University",
    shortName: "McGill",
    city: "Montreal",
    country: "Canada",
    countryId: "ca",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Entrance awards exist; most international undergraduates pay international tuition without full-need aid.",
    },
    tuitionIntlUsd: 32000,
    tuitionNote: "International tuition varies by faculty; living costs in Montreal are moderate for Canada.",
    selectivity: "very",
    application: "McGill applicant portal",
    deadlines: [{ label: "Most undergraduate programs", date: "Jan 15" }],
    english: "IELTS/TOEFL accepted; minima depend on program.",
    notes: "English-language research university in Montreal with strong life sciences and CS.",
    sources: [
      { label: "McGill undergraduate admissions", url: "https://www.mcgill.ca/undergraduate-admissions/" },
    ],
  },
  {
    id: "ubc",
    name: "University of British Columbia",
    shortName: "UBC",
    city: "Vancouver",
    country: "Canada",
    countryId: "ca",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "International scholars programs exist; most students still rely on family funds or external awards.",
    },
    tuitionIntlUsd: 42000,
    tuitionNote: "International tuition plus Vancouver living costs are significant.",
    selectivity: "very",
    application: "EducationPlannerBC / UBC application",
    deadlines: [{ label: "Winter Session (typical)", date: "Jan 15" }],
    english: "IELTS/TOEFL/Duolingo accepted for English-language proof.",
    notes: "Large research university with strong CS, engineering, and biological sciences.",
    sources: [
      { label: "UBC undergraduate admissions", url: "https://you.ubc.ca/applying-ubc/" },
    ],
  },
  {
    id: "mcmaster",
    name: "McMaster University",
    shortName: "McMaster",
    city: "Hamilton",
    country: "Canada",
    countryId: "ca",
    programs: ["cs", "engineering", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary: "Some awards for internationals; full-need institutional aid is uncommon.",
    },
    tuitionIntlUsd: 38000,
    tuitionNote: "International fees vary by program; health sciences pathways are especially competitive.",
    selectivity: "very",
    application: "OUAC",
    deadlines: [{ label: "OUAC (typical)", date: "Jan 15" }],
    english: "IELTS/TOEFL accepted; program minima vary.",
    notes: "Particularly known for health and life sciences alongside engineering and CS.",
    sources: [
      {
        label: "McMaster future students",
        url: "https://future.mcmaster.ca/",
      },
    ],
  },
  {
    id: "khalifa",
    name: "Khalifa University",
    shortName: "Khalifa",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
    countryId: "ae",
    programs: ["cs", "engineering", "biology"],
    research: "high",
    aid: {
      kind: "generous-need",
      summary:
        "Competitive scholarships and sponsorship pathways are a major part of international affordability here.",
    },
    tuitionIntlUsd: 28000,
    tuitionNote: "Sticker tuition is below many U.S. privates; scholarship outcomes vary by applicant.",
    selectivity: "very",
    application: "Khalifa University admissions portal",
    deadlines: [{ label: "Fall intake (typical)", date: "Apr 30" }],
    english: "IELTS/TOEFL typically required for English-medium programs.",
    notes: "STEM-focused research university in Abu Dhabi.",
    sources: [
      { label: "Khalifa University admissions", url: "https://www.ku.ac.ae/admissions" },
    ],
  },
  {
    id: "aus",
    name: "American University of Sharjah",
    shortName: "AUS",
    city: "Sharjah",
    country: "United Arab Emirates",
    countryId: "ae",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "moderate",
    aid: {
      kind: "limited-intl",
      summary:
        "Merit scholarships are available; full need-based packages are not the default model.",
    },
    tuitionIntlUsd: 26000,
    tuitionNote: "Lower sticker than many U.S./NYUAD peers; confirm current fee schedule.",
    selectivity: "moderately",
    application: "AUS online application",
    deadlines: [{ label: "Fall admission (typical)", date: "Jun 30" }],
    english: "TOEFL/IELTS or equivalent English proficiency usually required.",
    notes: "American-style curriculum in the UAE with engineering and business strength.",
    sources: [
      { label: "AUS admissions", url: "https://www.aus.edu/admissions" },
    ],
  },
  {
    id: "uva",
    name: "University of Amsterdam",
    shortName: "UvA",
    city: "Amsterdam",
    country: "Netherlands",
    countryId: "nl",
    programs: ["cs", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary:
        "Non-EU institutional fees are far below typical U.S. private tuition; scholarships are limited.",
    },
    tuitionIntlUsd: 14000,
    tuitionNote: "Non-EU bachelor fees are typically in the low-to-mid teens (USD equivalent).",
    selectivity: "moderately",
    application: "Studielink / UvA",
    deadlines: [{ label: "Non-EU bachelor (typical)", date: "Jan 15" }],
    english: "IELTS/TOEFL required for English-taught programmes.",
    notes: "English-taught bachelor options exist; check language of instruction per programme.",
    sources: [
      {
        label: "UvA bachelor's programmes",
        url: "https://www.uva.nl/en/education/bachelor-s/bachelor-s.html",
      },
    ],
  },
  {
    id: "tue",
    name: "Eindhoven University of Technology",
    shortName: "TU/e",
    city: "Eindhoven",
    country: "Netherlands",
    countryId: "nl",
    programs: ["cs", "engineering"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary:
        "Institutional fees for non-EU students remain well below U.S. private sticker prices.",
    },
    tuitionIntlUsd: 15000,
    tuitionNote: "Affordability comes from lower fees, not U.S.-style full-need aid.",
    selectivity: "moderately",
    application: "Studielink / TU/e",
    deadlines: [{ label: "Non-EU bachelor (typical)", date: "Jan 15" }],
    english: "IELTS/TOEFL required for English-taught bachelor programmes.",
    notes: "Engineering- and technology-first campus with strong industry links.",
    sources: [
      {
        label: "TU/e bachelor programs",
        url: "https://www.tue.nl/en/education/bachelor-college",
      },
    ],
  },
  {
    id: "rwth",
    name: "RWTH Aachen University",
    shortName: "RWTH",
    city: "Aachen",
    country: "Germany",
    countryId: "de",
    programs: ["cs", "engineering"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary: "Public tuition is low; living costs and language of instruction are the main constraints.",
    },
    tuitionIntlUsd: 1000,
    tuitionNote: "Semester fees are modest; confirm any non-EU tuition rules for the chosen programme.",
    selectivity: "moderately",
    application: "RWTH / uni-assist (programme-dependent)",
    deadlines: [{ label: "Winter semester (typical)", date: "Jul 15" }],
    english: "Many bachelor programmes are German-taught; English options are limited at bachelor level.",
    notes: "One of Germany’s major technical universities. Language planning is essential.",
    sources: [
      { label: "RWTH degree programs", url: "https://www.rwth-aachen.de/cms/root/Studium/~eqw/Studiengaenge/" },
    ],
  },
  {
    id: "heidelberg",
    name: "Heidelberg University",
    shortName: "Heidelberg",
    city: "Heidelberg",
    country: "Germany",
    countryId: "de",
    programs: ["biology", "economics", "undecided"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary: "Public university fees are low; Baden-Württemberg may charge modest non-EU tuition.",
    },
    tuitionIntlUsd: 3500,
    tuitionNote: "Living costs matter more than tuition; language of instruction varies by programme.",
    selectivity: "moderately",
    application: "University portal / uni-assist",
    deadlines: [{ label: "Winter semester (typical)", date: "Jul 15" }],
    english: "Many bachelor programmes are German-taught; check each subject.",
    notes: "Strong life sciences and research profile; confirm English-taught options carefully.",
    sources: [
      {
        label: "Heidelberg prospective students",
        url: "https://www.uni-heidelberg.de/en/study",
      },
    ],
  },
  {
    id: "epfl",
    name: "École Polytechnique Fédérale de Lausanne",
    shortName: "EPFL",
    city: "Lausanne",
    country: "Switzerland",
    countryId: "ch",
    programs: ["cs", "engineering", "biology"],
    research: "high",
    aid: {
      kind: "low-tuition",
      summary: "Tuition is low by international standards; Swiss living costs are high.",
    },
    tuitionIntlUsd: 1600,
    tuitionNote: "Tuition is not the main barrier; living costs and academic intensity are.",
    selectivity: "very",
    application: "EPFL application portal",
    deadlines: [{ label: "Bachelor (typical)", date: "Apr 30" }],
    english: "Bachelor programmes are primarily French-taught; confirm language requirements.",
    notes: "World-class technical university. Language of instruction is a real constraint at bachelor level.",
    sources: [
      { label: "EPFL bachelor admission", url: "https://www.epfl.ch/education/bachelor/" },
    ],
  },
  {
    id: "jhu",
    name: "Johns Hopkins University",
    shortName: "Johns Hopkins",
    city: "Baltimore",
    country: "United States",
    countryId: "us",
    programs: ["biology", "engineering", "cs", "economics", "undecided"],
    research: "high",
    aid: {
      kind: "need-aware-intl",
      summary:
        "Meets full demonstrated need for admitted students; international admissions are need-aware.",
    },
    tuitionIntlUsd: 63000,
    tuitionNote: "If admitted with need, institutional aid typically meets demonstrated need.",
    selectivity: "extremely",
    application: "Common App / Coalition",
    deadlines: [
      { label: "Early Decision I", date: "Nov 1" },
      { label: "Regular Decision", date: "Jan 2" },
    ],
    english: "TOEFL/IELTS/Duolingo accepted when English proficiency proof is required.",
    notes: "Especially strong for life sciences and biomedical research pathways.",
    sources: [
      { label: "Johns Hopkins undergraduate admissions", url: "https://apply.jhu.edu/" },
    ],
  },
  {
    id: "williams",
    name: "Williams College",
    shortName: "Williams",
    city: "Williamstown",
    country: "United States",
    countryId: "us",
    programs: ["economics", "biology", "cs", "undecided"],
    research: "moderate",
    aid: {
      kind: "meets-full-need",
      summary:
        "Need-blind for all applicants, including internationals, and meets full demonstrated need.",
    },
    tuitionIntlUsd: 68000,
    tuitionNote: "Aid is need-based; strong option when full private aid is required.",
    selectivity: "extremely",
    application: "Common App / QuestBridge",
    deadlines: [
      { label: "Early Decision", date: "Nov 15" },
      { label: "Regular Decision", date: "Jan 8" },
    ],
    english: "English proficiency may be required if prior schooling was not in English.",
    notes: "Selective liberal-arts college with tutorial-style economics and strong sciences.",
    sources: [
      { label: "Williams admission", url: "https://admission.williams.edu/" },
    ],
  },
  {
    id: "kcl",
    name: "King's College London",
    shortName: "King's",
    city: "London",
    country: "United Kingdom",
    countryId: "uk",
    programs: ["biology", "economics", "cs", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary: "International scholarships exist but are competitive; full-need aid is uncommon.",
    },
    tuitionIntlUsd: 34000,
    tuitionNote: "Overseas fees are programme-specific; confirm the course fee page.",
    selectivity: "very",
    application: "UCAS",
    deadlines: [{ label: "UCAS equal consideration", date: "Jan 14" }],
    english: "IELTS typically 6.5–7.0 depending on programme.",
    notes: "Strong life sciences and social sciences in central London.",
    sources: [
      {
        label: "King's undergraduate",
        url: "https://www.kcl.ac.uk/study/undergraduate",
      },
    ],
  },
  {
    id: "hku",
    name: "The University of Hong Kong",
    shortName: "HKU",
    city: "Hong Kong",
    country: "Hong Kong",
    countryId: "hk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Entrance scholarships exist; most non-local undergraduates still face substantial fees without full-need aid.",
    },
    tuitionIntlUsd: 22000,
    tuitionNote: "Non-local tuition is programme-dependent; living costs in Hong Kong are high.",
    selectivity: "very",
    application: "HKU online application",
    deadlines: [{ label: "Main round (typical)", date: "Nov 15" }],
    english: "IELTS/TOEFL typically required unless exempt by prior English-medium education.",
    notes: "Comprehensive research university with English-medium undergraduate teaching.",
    sources: [
      { label: "HKU admissions", url: "https://admissions.hku.hk/" },
    ],
  },
  {
    id: "hkust",
    name: "The Hong Kong University of Science and Technology",
    shortName: "HKUST",
    city: "Hong Kong",
    country: "Hong Kong",
    countryId: "hk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary:
        "Merit and targeted scholarships are available; full need-based packages are not the default.",
    },
    tuitionIntlUsd: 22000,
    tuitionNote: "Non-local fees plus living costs; scholarships are competitive.",
    selectivity: "extremely",
    application: "HKUST online application",
    deadlines: [{ label: "Early round (typical)", date: "Nov 20" }],
    english: "IELTS/TOEFL or equivalent English proficiency usually required.",
    notes: "STEM- and business-strong research university; English is the language of instruction.",
    sources: [
      { label: "HKUST undergraduate admissions", url: "https://join.hkust.edu.hk/" },
    ],
  },
  {
    id: "cuhk",
    name: "The Chinese University of Hong Kong",
    shortName: "CUHK",
    city: "Hong Kong",
    country: "Hong Kong",
    countryId: "hk",
    programs: ["cs", "engineering", "economics", "biology", "undecided"],
    research: "high",
    aid: {
      kind: "limited-intl",
      summary: "Scholarships for non-local students exist; need-guaranteed aid is uncommon.",
    },
    tuitionIntlUsd: 20000,
    tuitionNote: "Non-local tuition is lower than many U.S. privates; living costs remain significant.",
    selectivity: "very",
    application: "CUHK online application",
    deadlines: [{ label: "Advance offer / main (typical)", date: "Nov 16" }],
    english: "IELTS/TOEFL typically required for English-taught programmes.",
    notes: "Comprehensive university with college system and strong research profile.",
    sources: [
      {
        label: "CUHK non-JUPAS admissions",
        url: "https://admission.cuhk.edu.hk/",
      },
    ],
  },
];

export const countryLabels: Record<string, string> = {
  us: "United States",
  ca: "Canada",
  uk: "United Kingdom",
  ae: "United Arab Emirates",
  hk: "Hong Kong",
  nl: "Netherlands",
  de: "Germany",
  ch: "Switzerland",
};

export const fieldLabels: Record<string, string> = {
  cs: "Computer science",
  engineering: "Engineering",
  economics: "Economics",
  biology: "Biology / life sciences",
  undecided: "Undeclared / open",
};
